# Generated by Django 5.2.3 on 2025-07-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_seller_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofile', to='store.sellerprofile'),
        ),
    ]
