# Generated by Django 5.2.3 on 2025-07-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='store.sellerprofile'),
        ),
    ]
