# Generated by Django 5.2.3 on 2025-07-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_seller_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_profile',
        ),
    ]
