# Generated by Django 5.2.3 on 2025-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_seller_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='order_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
