# Generated by Django 5.2.3 on 2025-07-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_payments_merchant_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='merchant_reference',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='order_tracking_id',
        ),
    ]
